// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/afucloud-buttons/CurrentButtons.tsx": () => import("../components/mockups/afucloud-buttons/CurrentButtons.tsx"),
  "./components/mockups/afucloud-docs/Current.tsx": () => import("../components/mockups/afucloud-docs/Current.tsx")
};
